### ISSUE TITLE
Only works in Safari

### ISSUE THREAD

**Issue by stepkurniawan** [rcalme/svg-to-stl#3]
I tested with 
1. MacOS Sierra 10.12.5 - Safari Version 10.1.1 (12603.2.4) -> it works perfectly
2. MacOS Sierra 10.12.5 - Google Chrome Version 58.0.3029.110 (64-bit) -> It got upside down, and it does not work when there is a white area inside a black line. A ring for example. By extruding the white area inside, rather than the line.
Edited: the white area inside (so-called hole) is fixable using the reverse winding option.

**Comment by rcalme** [comment]
Colors don't actually have anything to do with the structure being rendered. Fill colors that match the background won't be rendered as hollow just because of their color.

https://github.com/rcalme/svg-to-stl#known-problems

The open libraries that I use shouldn't work differently across different browsers, but I suppose it's possible.
